import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'ru') ? saved : 'ru';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, fallback?: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return fallback || key;
      }
    }
    
    return typeof value === 'string' ? value : (fallback || key);
  };

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

const translations = {
  ru: {
    nav: {
      dashboard: 'Главная',
      statistics: 'Статистика',
      leaderboard: 'Рейтинг',
      members: 'Участники',
      shop: 'Магазин',
      inventory: 'Инвентарь',
      convert: 'Конвертация',
      music: 'Музыка',
      news: 'Новости',
      forum: 'Форум',
      requests: 'Запросы',
      videos: 'Видео',
      about: 'О клане',
      roblox: 'Roblox',
      menu: 'Меню',
    },
    dashboard: {
      title: 'CLAN COMMAND',
      description: 'Элитный игровой клан с передовыми технологиями и AI-помощью',
      online: 'Онлайн',
      members: 'Участники',
      wins: 'Побед',
      rating: 'Рейтинг',
      activity: 'Активность',
      topMembers: 'Топ Участников',
      latestNews: 'Последние Новости',
      readMore: 'Подробнее',
      viewAll: 'Смотреть Все',
    },
    shop: {
      title: 'Магазин LumiCoin',
      description: 'Приобретайте уникальные предметы, бустеры и услуги за LumiCoin',
      discordIdTitle: 'Discord ID для покупки',
      discordIdDescription: 'Введите свой Discord ID чтобы совершать покупки',
      discordIdPlaceholder: 'Введите ваш Discord ID (например: 123456789)',
      allItems: 'Все предметы',
      boosters: 'Бустеры',
      badges: 'Бейджи',
      titles: 'Титулы',
      banners: 'Баннеры',
      collectibles: 'Коллекционные',
      services: 'Услуги',
      roles: 'Роли',
      buy: 'Купить',
      buying: 'Покупка...',
      outOfStock: 'Нет в наличии',
      stock: 'Осталось',
      noItems: 'Предметы не найдены',
    },
    inventory: {
      title: 'Инвентарь',
      description: 'Ваши купленные предметы и активные эффекты',
      discordIdTitle: 'Discord ID',
      discordIdDescription: 'Введите Discord ID для просмотра инвентаря',
      discordIdPlaceholder: 'Введите Discord ID',
      quantity: 'Количество',
      acquired: 'Получено',
      expires: 'Истекает',
      equipped: 'Экипировано',
      use: 'Использовать',
      noItems: 'Инвентарь пуст',
    },
    forum: {
      title: 'Форум',
      description: 'Обсуждения и общение участников клана',
      createTopic: 'Создать Тему',
      newTopic: 'Новая Тема',
      topicTitle: 'Заголовок',
      author: 'Автор',
      content: 'Содержание',
      create: 'Создать',
      reply: 'Ответить',
      replies: 'Ответов',
      views: 'Просмотров',
      pinned: 'Закреплено',
      locked: 'Закрыта для комментариев',
      noTopics: 'Нет тем для обсуждения',
    },
    requests: {
      title: 'Запросы',
      description: 'Подавайте заявки на роли или задавайте вопросы администраторам',
      createRequest: 'Создать Запрос',
      newRequest: 'Новый Запрос',
      username: 'Имя пользователя',
      requestType: 'Тип запроса',
      moderator: 'Модератор',
      helper: 'Помощник',
      admin: 'Администратор',
      question: 'Вопрос',
      message: 'Сообщение',
      send: 'Отправить',
      pending: 'Ожидает',
      approved: 'Одобрено',
      rejected: 'Отклонено',
      adminResponse: 'Ответ администратора',
      noRequests: 'Нет запросов',
    },
    music: {
      title: 'Музыкальный Плеер',
      description: 'Управление музыкой в Discord голосовых каналах',
      searchPlaceholder: 'YouTube URL или поисковый запрос',
      play: 'Воспроизвести',
      pause: 'Пауза',
      resume: 'Продолжить',
      skip: 'Пропустить',
      stop: 'Остановить',
      shuffle: 'Перемешать',
      loop: 'Повтор',
      volume: 'Громкость',
      nowPlaying: 'Сейчас играет',
      queue: 'Очередь',
      noQueue: 'Очередь пуста',
      selectChannel: 'Выберите голосовой канал',
      unauthorized: 'Доступ запрещён',
      loginRequired: 'Войдите в админ панель для управления музыкой',
    },
    news: {
      title: 'Новости Клана',
      description: 'Последние события и объявления',
      createNews: 'Создать Новость',
      newNews: 'Новая Новость',
      newsTitle: 'Заголовок',
      category: 'Категория',
      authorName: 'Имя автора',
      imageUrl: 'URL изображения',
      publish: 'Опубликовать',
      noNews: 'Нет новостей',
    },
    leaderboard: {
      title: 'Рейтинг Игроков',
      description: 'Топ участников клана по активности и достижениям',
      overallRating: 'Общий Рейтинг',
      joined: 'Присоединился',
      legend: 'Легенда',
      elite: 'Элита',
      veteran: 'Ветеран',
      fighter: 'Боец',
    },
    members: {
      title: 'Участники Клана',
      description: 'Все участники нашего клана',
      totalMembers: 'Всего участников',
      messages: 'Сообщений',
      voiceTime: 'Время в голосовых',
      reactions: 'Реакций',
      joined: 'Присоединился',
    },
    about: {
      title: 'О',
      description: 'История и достижения нашего клана',
      values: 'Наши Ценности',
      rules: 'Правила Клана',
      achievements: 'Достижения',
      history: 'История',
      honesty: 'Честность',
      honestyDesc: 'Мы играем честно и открыто',
      unity: 'Единство',
      unityDesc: 'Команда - наша главная сила',
      mastery: 'Мастерство',
      masteryDesc: 'Постоянное совершенствование навыков',
      victory: 'Победа',
      victoryDesc: 'Стремимся к лучшим результатам',
      rule1: 'Уважайте всех участников клана и соперников',
      rule2: 'Участвуйте активно в командных мероприятиях',
      rule3: 'Следуйте тактическим указаниям лидеров',
      rule4: 'Помогайте новым участникам адаптироваться',
      rule5: 'Используйте голосовую связь во время матчей',
      rule6: 'Регулярно тренируйтесь и улучшайте навыки',
      rule7: 'Делитесь полезной информацией с командой',
      rule8: 'Соблюдайте честность и спортивное поведение',
      achievement1Title: 'Чемпионы региона',
      achievement1Desc: '1-е место в региональном турнире 2024',
      achievement2Title: 'Лучшая команда',
      achievement2Desc: 'Награда за командную работу',
      achievement3Title: 'Топ-10 в мире',
      achievement3Desc: 'Входим в топ-10 мировых рейтингов',
      achievement4Title: 'Рекорд серии побед',
      achievement4Desc: '25 побед подряд в сезоне',
    },
    statistics: {
      title: 'Статистика',
      description: 'Подробная аналитика активности участников',
      memberActivity: 'Активность Участников',
      topContributors: 'Топ Контрибуторов',
      growthTrend: 'Тенденция Роста',
      monthlyActivity: 'Активность по месяцам',
    },
    login: {
      title: 'Добро пожаловать',
      description: 'Войдите через Discord для доступа к магазину или продолжите как гость',
      discord: 'Войти через Discord',
      guest: 'Продолжить как гость',
      or: 'или',
      guestInfo: 'В гостевом режиме вы можете просматривать контент, но не сможете совершать покупки',
      logout: 'Выйти',
    },
    convert: {
      title: 'Конвертация в Robux',
      description: 'Конвертируйте LumiCoin в Robux',
      systemDisabled: 'Система конвертации отключена',
      discordIdLabel: 'Ваш Discord ID',
      discordIdPlaceholder: 'Введите Discord ID',
      usernameLabel: 'Ваше имя пользователя',
      usernamePlaceholder: 'Введите имя',
      robloxUsernameLabel: 'Roblox имя пользователя',
      robloxUsernamePlaceholder: 'Введите Roblox имя',
      lumiCoinAmountLabel: 'Сумма LumiCoin',
      lumiCoinAmountPlaceholder: 'Введите сумму',
      exchangeRate: 'Курс обмена',
      minAmount: 'Минимальная сумма',
      maxAmount: 'Максимальная сумма',
      youWillReceive: 'Вы получите',
      submit: 'Отправить запрос',
      submitting: 'Отправка...',
      yourRequests: 'Ваши запросы',
      requestId: 'ID запроса',
      robloxUsername: 'Roblox имя',
      amount: 'Сумма',
      robux: 'Robux',
      status: 'Статус',
      date: 'Дата',
      pending: 'Ожидание',
      approved: 'Одобрено',
      rejected: 'Отклонено',
      completed: 'Завершено',
      adminNote: 'Заметка администратора',
      noRequests: 'У вас нет запросов',
      requestSent: 'Запрос отправлен!',
      requestSentDesc: 'Ваш запрос на конвертацию отправлен администрации',
      errorTitle: 'Ошибка',
      errorSending: 'Не удалось отправить запрос',
      fillAllFields: 'Заполните все поля',
      fillAllFieldsDesc: 'Пожалуйста, введите всю необходимую информацию',
      invalidAmount: 'Неверная сумма',
      invalidAmountDesc: 'Введите корректное число LumiCoins',
    },
    coin_monitoring: {
      title: 'Мониторинг LumiCoin',
      page_description: 'Отслеживание всех транзакций заработка и трат LumiCoin',
      filters: 'Фильтры',
      transaction_type: 'Тип транзакции',
      all: 'Все',
      earned: 'Заработано',
      spent: 'Потрачено',
      discord_id: 'Discord ID',
      enter_discord_id: 'Введите Discord ID...',
      refresh: 'Обновить',
      auto_refresh: 'Автообновление каждые 30 секунд',
      recent_transactions: 'Последние транзакции',
      username: 'Пользователь',
      amount: 'Сумма',
      type: 'Тип',
      source: 'Источник',
      description: 'Описание',
      timestamp: 'Время',
      no_transactions: 'Транзакций не найдено',
      total_earned: 'Всего заработано',
      total_spent: 'Всего потрачено',
      net_balance: 'Чистый баланс',
      total_records: 'Всего записей',
      showing: 'Показано',
      of: 'из',
      previous: 'Назад',
      next: 'Далее',
    },
    common: {
      loading: 'Загрузка...',
      error: 'Ошибка',
      success: 'Успешно!',
      cancel: 'Отмена',
      save: 'Сохранить',
      delete: 'Удалить',
      edit: 'Редактировать',
      close: 'Закрыть',
      search: 'Поиск',
      filter: 'Фильтр',
      viewMore: 'Показать больше',
      back: 'Назад в Админпанель',
      balance: 'Баланс',
    },
    roblox: {
      title: 'Roblox Трекер',
      subtitle: 'Отслеживайте активность любого игрока Roblox в реальном времени',
      playerSearch: 'Поиск игрока',
      gameSearch: 'Поиск игр',
      searchPlaceholder: 'Введите никнейм в Roblox...',
      gamePlaceholder: 'Название игры или ссылка roblox.com/games/...',
      playerInGamePlaceholder: 'Никнейм игрока — узнать, во что играет...',
      playerBadgesPlaceholder: 'Никнейм — значки игрока в этой игре',
      find: 'Найти',
      recentSearches: 'Недавние поиски',
      recentGames: 'Недавние игры',
      clear: 'Очистить',
      loadingData: 'Загрузка данных из Roblox...',
      searchingGames: 'Поиск игр...',
      loadingBadges: 'Загрузка значков...',
      userNotFound: 'Пользователь не найден',
      checkUsername: 'Проверьте правильность никнейма',
      banned: 'Заблокирован',
      profile: 'Профиль',
      created: 'Создан',
      age: 'Возраст',
      lastSeen: 'Был',
      friends: 'Друзья',
      followers: 'Подписчики',
      following: 'Подписки',
      nowPlaying: 'Сейчас играет',
      playing: 'играют',
      visits: 'посещений',
      join: 'Присоединиться',
      gamePage: 'Страница игры',
      inGame: 'В игре',
      gameHidden: 'Информация об игре скрыта настройками приватности',
      online: 'Сейчас онлайн',
      onRoblox: 'На сайте Roblox',
      offline: 'Оффлайн',
      lastOnline: 'Последний раз в сети',
      unknownTime: 'Время последнего входа неизвестно',
      inStudio: 'В Roblox Studio',
      developing: 'Занимается разработкой игры',
      autoRefresh: 'Авто-обновление каждые 30 секунд',
      startSearch: 'Начните поиск',
      startSearchDesc: 'Введите никнейм любого игрока Roblox, чтобы увидеть его профиль, статус и текущую игру',
      gameSearchTitle: 'Поиск игр Roblox',
      gameSearchDesc: 'Введите название игры или вставьте ссылку (roblox.com/games/...) чтобы найти информацию: онлайн, рейтинг, ссылку для запуска',
      gamesNotFound: 'Игры не найдены. Попробуйте другой запрос или вставьте ссылку.',
      found: 'Найдено',
      games: 'игр',
      inGameLabel: 'в игре',
      visitsLabel: 'визитов',
      play: 'Играть',
      page: 'Страница',
      backToResults: 'Назад к результатам',
      by: 'от',
      nowPlayingCount: 'Сейчас играют',
      totalVisits: 'Посещений',
      favorites: 'В избранном',
      rating: 'Рейтинг',
      likes: 'Лайки',
      maxPlayers: 'Макс. игроков',
      createdDate: 'Создана',
      badgesInGame: 'Значки в этой игре',
      noBadges: 'Ни одного значка не получено',
      more: 'ещё',
      playsIn: 'Играет в',
      open: 'Открыть',
      inGameHidden: 'В игре (информация скрыта)',
      onlineOnSite: 'Онлайн на сайте Roblox',
      offlineStatus: 'Оффлайн',
      justNow: 'Только что',
      minAgo: 'мин. назад',
      hoursAgo: 'ч. назад',
      daysAgo: 'дн. назад',
      lessThanMonth: 'Меньше месяца',
      months: 'мес.',
      years: 'г.',
    },
  },
  en: {
    nav: {
      dashboard: 'Dashboard',
      statistics: 'Statistics',
      leaderboard: 'Leaderboard',
      members: 'Members',
      shop: 'Shop',
      inventory: 'Inventory',
      convert: 'Convert',
      music: 'Music',
      news: 'News',
      forum: 'Forum',
      requests: 'Requests',
      videos: 'Videos',
      about: 'About',
      roblox: 'Roblox',
      menu: 'Menu',
    },
    dashboard: {
      title: 'CLAN COMMAND',
      description: 'Elite gaming clan with advanced technologies and AI assistance',
      online: 'Online',
      members: 'Members',
      wins: 'Wins',
      rating: 'Rating',
      activity: 'Activity',
      topMembers: 'Top Members',
      latestNews: 'Latest News',
      readMore: 'Read More',
      viewAll: 'View All',
    },
    shop: {
      title: 'LumiCoin Shop',
      description: 'Purchase unique items, boosters and services with LumiCoin',
      discordIdTitle: 'Discord ID for purchase',
      discordIdDescription: 'Enter your Discord ID to make purchases',
      discordIdPlaceholder: 'Enter your Discord ID (e.g.: 123456789)',
      allItems: 'All items',
      boosters: 'Boosters',
      badges: 'Badges',
      titles: 'Titles',
      banners: 'Banners',
      collectibles: 'Collectibles',
      services: 'Services',
      roles: 'Roles',
      buy: 'Buy',
      buying: 'Buying...',
      outOfStock: 'Out of stock',
      stock: 'In stock',
      noItems: 'No items found',
    },
    inventory: {
      title: 'Inventory',
      description: 'Your purchased items and active effects',
      discordIdTitle: 'Discord ID',
      discordIdDescription: 'Enter Discord ID to view inventory',
      discordIdPlaceholder: 'Enter Discord ID',
      quantity: 'Quantity',
      acquired: 'Acquired',
      expires: 'Expires',
      equipped: 'Equipped',
      use: 'Use',
      noItems: 'Inventory is empty',
    },
    forum: {
      title: 'Forum',
      description: 'Discussions and communication of clan members',
      createTopic: 'Create Topic',
      newTopic: 'New Topic',
      topicTitle: 'Title',
      author: 'Author',
      content: 'Content',
      create: 'Create',
      reply: 'Reply',
      replies: 'Replies',
      views: 'Views',
      pinned: 'Pinned',
      locked: 'Locked for comments',
      noTopics: 'No discussion topics',
    },
    requests: {
      title: 'Requests',
      description: 'Submit role applications or ask administrators questions',
      createRequest: 'Create Request',
      newRequest: 'New Request',
      username: 'Username',
      requestType: 'Request type',
      moderator: 'Moderator',
      helper: 'Helper',
      admin: 'Administrator',
      question: 'Question',
      message: 'Message',
      send: 'Send',
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      adminResponse: 'Admin response',
      noRequests: 'No requests',
    },
    music: {
      title: 'Music Player',
      description: 'Control music in Discord voice channels',
      searchPlaceholder: 'YouTube URL or search query',
      play: 'Play',
      pause: 'Pause',
      resume: 'Resume',
      skip: 'Skip',
      stop: 'Stop',
      shuffle: 'Shuffle',
      loop: 'Loop',
      volume: 'Volume',
      nowPlaying: 'Now Playing',
      queue: 'Queue',
      noQueue: 'Queue is empty',
      selectChannel: 'Select voice channel',
      unauthorized: 'Access Denied',
      loginRequired: 'Login to admin panel to control music',
    },
    news: {
      title: 'Clan News',
      description: 'Latest events and announcements',
      createNews: 'Create News',
      newNews: 'New News',
      newsTitle: 'Title',
      category: 'Category',
      authorName: 'Author name',
      imageUrl: 'Image URL',
      publish: 'Publish',
      noNews: 'No news',
    },
    leaderboard: {
      title: 'Player Ranking',
      description: 'Top clan members by activity and achievements',
      overallRating: 'Overall Rating',
      joined: 'Joined',
      legend: 'Legend',
      elite: 'Elite',
      veteran: 'Veteran',
      fighter: 'Fighter',
    },
    members: {
      title: 'Clan Members',
      description: 'All members of our elite gaming clan',
      totalMembers: 'Total members',
      messages: 'Messages',
      voiceTime: 'Voice time',
      reactions: 'Reactions',
      joined: 'Joined',
    },
    about: {
      title: 'About',
      description: 'History and achievements of our clan',
      values: 'Our Values',
      rules: 'Clan Rules',
      achievements: 'Achievements',
      history: 'History',
      honesty: 'Honesty',
      honestyDesc: 'We play fair and open',
      unity: 'Unity',
      unityDesc: 'Team is our main strength',
      mastery: 'Mastery',
      masteryDesc: 'Continuous skill improvement',
      victory: 'Victory',
      victoryDesc: 'Striving for the best results',
      rule1: 'Respect all clan members and opponents',
      rule2: 'Participate actively in team events',
      rule3: 'Follow tactical guidance from leaders',
      rule4: 'Help new members adapt',
      rule5: 'Use voice communication during matches',
      rule6: 'Train regularly and improve skills',
      rule7: 'Share useful information with the team',
      rule8: 'Maintain honesty and sportsmanship',
      achievement1Title: 'Regional Champions',
      achievement1Desc: '1st place in regional tournament 2024',
      achievement2Title: 'Best Team',
      achievement2Desc: 'Award for teamwork',
      achievement3Title: 'Top-10 Worldwide',
      achievement3Desc: 'Ranked in top-10 global rankings',
      achievement4Title: 'Win Streak Record',
      achievement4Desc: '25 consecutive wins in a season',
    },
    statistics: {
      title: 'Statistics',
      description: 'Detailed analytics of member activity',
      memberActivity: 'Member Activity',
      topContributors: 'Top Contributors',
      growthTrend: 'Growth Trend',
      monthlyActivity: 'Monthly Activity',
    },
    login: {
      title: 'Welcome',
      description: 'Login via Discord to access the shop or continue as a guest',
      discord: 'Login with Discord',
      guest: 'Continue as Guest',
      or: 'or',
      guestInfo: 'In guest mode you can view content but cannot make purchases',
      logout: 'Logout',
    },
    convert: {
      title: 'Convert to Robux',
      description: 'Convert LumiCoin to Robux',
      systemDisabled: 'Conversion system is disabled',
      discordIdLabel: 'Your Discord ID',
      discordIdPlaceholder: 'Enter Discord ID',
      usernameLabel: 'Your username',
      usernamePlaceholder: 'Enter username',
      robloxUsernameLabel: 'Roblox username',
      robloxUsernamePlaceholder: 'Enter Roblox username',
      lumiCoinAmountLabel: 'LumiCoin amount',
      lumiCoinAmountPlaceholder: 'Enter amount',
      exchangeRate: 'Exchange rate',
      minAmount: 'Minimum amount',
      maxAmount: 'Maximum amount',
      youWillReceive: 'You will receive',
      submit: 'Submit Request',
      submitting: 'Submitting...',
      yourRequests: 'Your Requests',
      requestId: 'Request ID',
      robloxUsername: 'Roblox username',
      amount: 'Amount',
      robux: 'Robux',
      status: 'Status',
      date: 'Date',
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      completed: 'Completed',
      adminNote: 'Admin note',
      noRequests: 'You have no requests',
      requestSent: 'Request sent!',
      requestSentDesc: 'Your conversion request has been sent to administration',
      errorTitle: 'Error',
      errorSending: 'Failed to send request',
      fillAllFields: 'Fill all fields',
      fillAllFieldsDesc: 'Please enter all required information',
      invalidAmount: 'Invalid amount',
      invalidAmountDesc: 'Enter a valid LumiCoin number',
    },
    coin_monitoring: {
      title: 'LumiCoin Monitoring',
      page_description: 'Track all LumiCoin earning and spending transactions',
      filters: 'Filters',
      transaction_type: 'Transaction Type',
      all: 'All',
      earned: 'Earned',
      spent: 'Spent',
      discord_id: 'Discord ID',
      enter_discord_id: 'Enter Discord ID...',
      refresh: 'Refresh',
      auto_refresh: 'Auto-refreshing every 30 seconds',
      recent_transactions: 'Recent Transactions',
      username: 'Username',
      amount: 'Amount',
      type: 'Type',
      source: 'Source',
      description: 'Description',
      timestamp: 'Time',
      no_transactions: 'No transactions found',
      total_earned: 'Total Earned',
      total_spent: 'Total Spent',
      net_balance: 'Net Balance',
      total_records: 'Total Records',
      showing: 'Showing',
      of: 'of',
      previous: 'Previous',
      next: 'Next',
    },
    common: {
      loading: 'Loading...',
      error: 'Error',
      success: 'Success!',
      cancel: 'Cancel',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      close: 'Close',
      search: 'Search',
      filter: 'Filter',
      viewMore: 'View More',
      back: 'Back to Admin Panel',
      balance: 'Balance',
    },
    roblox: {
      title: 'Roblox Tracker',
      subtitle: 'Track the activity of any Roblox player in real time',
      playerSearch: 'Player Search',
      gameSearch: 'Game Search',
      searchPlaceholder: 'Enter Roblox username...',
      gamePlaceholder: 'Game name or roblox.com/games/... link',
      playerInGamePlaceholder: 'Player nickname — see what they play...',
      playerBadgesPlaceholder: 'Nickname — player badges in this game',
      find: 'Find',
      recentSearches: 'Recent searches',
      recentGames: 'Recent games',
      clear: 'Clear',
      loadingData: 'Loading data from Roblox...',
      searchingGames: 'Searching games...',
      loadingBadges: 'Loading badges...',
      userNotFound: 'User not found',
      checkUsername: 'Check the username',
      banned: 'Banned',
      profile: 'Profile',
      created: 'Created',
      age: 'Age',
      lastSeen: 'Seen',
      friends: 'Friends',
      followers: 'Followers',
      following: 'Following',
      nowPlaying: 'Now playing',
      playing: 'playing',
      visits: 'visits',
      join: 'Join',
      gamePage: 'Game page',
      inGame: 'In game',
      gameHidden: 'Game info hidden by privacy settings',
      online: 'Online now',
      onRoblox: 'On Roblox website',
      offline: 'Offline',
      lastOnline: 'Last online',
      unknownTime: 'Last login time unknown',
      inStudio: 'In Roblox Studio',
      developing: 'Developing a game',
      autoRefresh: 'Auto-refreshing every 30 seconds',
      startSearch: 'Start searching',
      startSearchDesc: 'Enter any Roblox player\'s username to see their profile, status and current game',
      gameSearchTitle: 'Search Roblox Games',
      gameSearchDesc: 'Enter a game name or paste a link (roblox.com/games/...) to find info: online count, rating, launch link',
      gamesNotFound: 'No games found. Try a different query or paste a link.',
      found: 'Found',
      games: 'games',
      inGameLabel: 'in game',
      visitsLabel: 'visits',
      play: 'Play',
      page: 'Page',
      backToResults: 'Back to results',
      by: 'by',
      nowPlayingCount: 'Playing now',
      totalVisits: 'Visits',
      favorites: 'Favorites',
      rating: 'Rating',
      likes: 'Likes',
      maxPlayers: 'Max players',
      createdDate: 'Created',
      badgesInGame: 'Badges in this game',
      noBadges: 'No badges earned',
      more: 'more',
      playsIn: 'Playing',
      open: 'Open',
      inGameHidden: 'In game (info hidden)',
      onlineOnSite: 'Online on Roblox',
      offlineStatus: 'Offline',
      justNow: 'Just now',
      minAgo: 'min ago',
      hoursAgo: 'h ago',
      daysAgo: 'd ago',
      lessThanMonth: 'Less than a month',
      months: 'mo.',
      years: 'y.',
    },
  },
};
